package arrow.meta.ide.resources

import com.intellij.openapi.util.IconLoader
import javax.swing.Icon

object ArrowIcons {
  val OPTICS: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-optics.svg")
  val OPTICS_PNG: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-optics.png")
  val NOTHING_PNG: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-nothing.png")
  val NOTHING: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-nothing.svg")
  val HKT_PNG: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-higher.png")
  val HKT: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-higher.svg")
  val BIND_PNG: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-bind.png")
  val BIND: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-bind.svg")
  val POLY_PNG: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-polymorphic.png")
  val POLY: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-polymorphic.svg")
  val PURE_PNG: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-pure.png")
  val PURE: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-pure.svg")
  val COPRODUCT_PNG: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-coproduct.png")
  val COPRODUCT: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-coproduct.svg")
  val PRODUCT_PNG: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-product.png")
  val PRODUCT: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-product.svg")
  val INTERSECTION: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-intersection.svg")
  val INTERSECTION_PNG: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-intersection.png")
  val NEGATION: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-negation.svg")
  val NEGATION_PNG: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-negation.png")
  val SUBTYPING: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-subtyping.svg")
  val SUBTYPING_PNG: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-subtyping.png")
  val SUBTYPING2: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-subtyping2.svg")
  val SUBTYPING2_PNG: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-subtyping2.png")
  val ICON1: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-icon1.svg")
  val ICON1_PNG: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-icon1.png")
  val ICON2: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-icon2.svg")
  val ICON2_PNG: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-icon2.png")
  val ICON3: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-icon3.svg")
  val ICON3_PNG: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-icon3.png")
  val ICON4: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-icon4.svg")
  val ICON4_PNG: Icon
    get() = IconLoader.getIcon("/arrow/meta/plugin/idea/icons/arrow-meta-icon4.png")
}
