name: Build

on:
  push:
    # Build is checked before publication
    branches-ignore:
      - master
  pull_request:
    # When following these names for our internal branches,
    # twice executions (push and pull_request) will be avoided
    branches-ignore:
      - 'fix*'
      - 'feature*'
      - 'doc*'
      - 'release*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64
    - name: Build with Gradle
      env:
        JAVA_OPTS: -Xms512m -Xmx1024m
      run: |
        ./gradlew clean build
