name: generate-tag

on:
  workflow_dispatch:
    branches: [main]
    inputs:
      stage:
        description: 'Stage'
        required: true
        default: 'auto'
        type: choice
        options:
          - 'alpha'
          - 'beta'
          - 'rc'
          - 'final'
          - 'auto'
      scope:
        description: 'Scope'
        required: true
        default: 'auto'
        type: choice
        options:
          - 'minor'
          - 'major'
          - 'auto'

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=false -Dorg.gradle.jvmargs="-Xmx5g -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'adopt'
          java-version: '15'

      - name: Gradle build
        run: ./gradlew  --full-stacktrace build "-Psemver.scope=${{ github.event.inputs.scope }}" "-Psemver.stage=${{ github.event.inputs.stage }}"

      - name: Stop Gradle daemons
        run: ./gradlew --stop

  generate-tag:
    runs-on: ubuntu-latest

    needs:
      - build

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN_GITHUB_ACTION }}

      - name: Set up Java
        uses: actions/setup-java@v3.0.0
        with:
          distribution: 'adopt'
          java-version: '15'

      - name: Generate Tag
        run: ./gradlew --full-stacktrace createSemverTag "-Psemver.scope=${{ github.event.inputs.scope }}" "-Psemver.stage=${{ github.event.inputs.stage }}"

      - name: Push
        run: git push --follow-tags

      - name: Stop Gradle daemons
        run: ./gradlew --stop