name: Build Artifacts

on: pull_request

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx5g -XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8"

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        jvm_target: [ '1.8', '11', '17' ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and test with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: -PjvmTargetVersion=${{ matrix.jvm_target }} build --scan --stacktrace -x apiCheck

      - name: Upload reports
        uses: actions/upload-artifact@v3
        with:
          name: 'reports-${{ matrix.os }}'
          path: '**/build/reports/**'

  update_api:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: apiDump

      - name: Stop Gradle daemons
        run: ./gradlew --stop

      - name: "Commit new API files"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update API files
          file_pattern: /**/api/*.api

  build_documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Create API Doc and validate, step 1"
        run: ./gradlew buildMetaDoc

      - name: "Create API Doc and validate, step 2"
        run: ./gradlew :arrow-meta:dokkaJekyll # :arrow-meta-docs:runAnk

      - name: "Build"
        env:
          JEKYLL_ENV: production
        run: |
          sudo gem install bundler
          bundle config set --local path 'vendor/bundle'
          sudo bundle install --gemfile docs/Gemfile
          BUNDLE_GEMFILE=docs/Gemfile bundle exec jekyll build -b /docs/meta -s docs/docs -d docs/build
